[package]
name = "fixcol"
version = "0.1.0"
edition = "2021"

[features]
experimental-write = []

[workspace]
members = ["fixcol-derive"]

[dependencies]
fixcol-derive = {path = "fixcol-derive"}

[dev-dependencies]
chrono = "0.4.38"
escargot = "0.5.12"
regex = "1.10.6"
tempfile = "3.12.0"
trybuild = "1.0.99"

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "habsburgs"
path = "examples/habsburgs/main.rs"
required-features = ["experimental-write"]
