[package]
name = "fixcol"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["fixcol-derive"]

[dependencies]
fixcol-derive = {path = "fixcol-derive"}

[dev-dependencies]
chrono = "0.4.38"
escargot = "0.5.12"
regex = "1.10.6"
trybuild = "1.0.99"
