name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          # - nightly

    steps:
    - uses: actions/checkout@v4
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run default tests
      run: cargo test --workspace
    - name: Run write-experimental tests
      run: cargo test --workspace  --features experimental-write
